// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wycyrahxjeruvqllbnuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5Y3lyYWh4amVydXZxbGxibnVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjI4ODMsImV4cCI6MjA2NTAzODg4M30.geuc6fjT9NyqBIfyPmtGkh_4MrZN7kYIyXcuiq6U27E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);